common/models/User.php
<?php

namespace common\models;

use Yii;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property integer $user_id
 * @property string $email
 * @property string $password
 * @property string $image
 * @property integer $role_id
 * @property integer $parent_id
 * @property string $created
 * @property string $updated
 * @property integer $status
 * @property string $auth_key
 * @property string $username
 *
 * @property Role $role
 * @property User $parent
 * @property User[] $childs
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    const STATUS_ENABLED = 1;
    const STATUS_DISABLED = 0;


    public $confirm;
    public $old_password;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['role_id', 'status'], 'integer'],
            [['created', 'updated', 'image'], 'safe'],
            [['email', 'username'], 'string', 'max' => 128],
            [['password', 'old_password', 'confirm'], 'string', 'max' => 32],
            [['email'], 'unique', 'on' => ['default']],
            [['email'], 'email'],
            [['email'], 'required', 'on' => 'forgotten'],
            [['email', 'password', 'status', 'role_id', 'username'], 'required', 'on' => 'new'],
            [['email', 'status', 'role_id', 'username'], 'required', 'on' => 'edit'],
            [['email', 'password'], 'required', 'on' => ['auth']],
            [['confirm', 'password', 'old_password'], 'required', 'on' => 'password_change'],
            [['confirm', 'password'], 'required', 'on' => 'reset'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_id' => Yii::t('user/user', 'ID'),
            'email' => Yii::t('user/user', 'E-mail'),
            'password' => Yii::t('user/user', 'Password'),
            'image' => Yii::t('user/user', 'Image'),
            'confirm' => Yii::t('user/user', 'Password confirm'),
            'old_password' => Yii::t('user/user', 'Old password'),
            'role_id' => Yii::t('user/user', 'Role'),
            'created' => Yii::t('user/user', 'Date added'),
            'updated' => Yii::t('user/user', 'Date modified'),
            'status' => Yii::t('user/user', 'Status'),
            'username' => Yii::t('user/user', 'Username'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRole()
    {
        return $this->hasOne(Role::className(), ['role_id' => 'role_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(self::className(), ['parent_id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChilds()
    {
        return $this->hasMany(self::className(), ['user_id' => 'parent_id']);
    }

    /**
     * @inheritdoc
     * @return UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserQuery(get_called_class());
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['auth_key' => $token, 'status' => static::STATUS_ENABLED]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getAttribute('user_id');
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->auth_key === $authKey;
    }

    /**
     * @param $email
     * @param $password
     * @param null $role
     * @return bool
     */
    public static function findByLogin($email, $password, $role = null)
    {
        /* @var $result User */
        $result = self::find()->andWhere(['email' => $email, 'password' => md5($password)])->one();

        if ($result && (!$role || $role == $result->role->name)) {
            Yii::$app->user->login($result);

            return true;
        } else {
            return false;
        }
    }

    /**
     * @param $email
     * @return null|User
     */
    public static function findByEmail($email)
    {
        return self::findOne(['email' => $email]);
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if ($this->scenario == 'new') {
            $this->setAttribute('password', md5($this->getAttribute('password')));
            $this->setAttribute('created', date('Y-m-d H:i:s'));
            $this->setAttribute('parent_id', Yii::$app->user->identity->getId());
        } elseif ($this->scenario == 'edit') {
            $user = (new User())->findOne($this->getPrimaryKey());

            if (md5($this->getAttribute('password')) != $user->password && $this->getAttribute('password') != $user->password) {
                $this->setAttribute('password', md5($this->getAttribute('password')));
            }
        }

        $this->setAttribute('updated', date('Y-m-d H:i:s'));

        return parent::beforeSave($insert);
    }

    /**
     * @return string
     */
    public function getPassword()
    {
        $result = self::findOne($this->user_id);

        return $result->password;
    }

    /**
     * @return bool
     */
    public function validatePassword()
    {
        $password = $this->getPassword();

        $_password = $this->getAttribute('password');

        if ($password == md5($this->old_password)) {
            if (md5($this->getAttribute('password')) != md5($this->confirm)) {
                $this->addError('confirm', Yii::t('user/user', 'New password and Confirm password must be the same!'));
            } else {
                $this->setAttribute('password', md5($this->getAttribute('password')));
            }

            if ($password == md5($_password)) {
                $this->addError('password', Yii::t('user/user', 'New and old passwords should not be the same!'));
                $this->setAttribute('password', $_password);
            }

        } else {
            $this->addError('old_password', Yii::t('user/user', 'Invalid old password!'));
        }

        return !$this->hasErrors();
    }

    /**
     * @param $string
     * @return string
     */
    public static function generateAuthKey($string)
    {
        return md5($string . Yii::$app->security->generateRandomString());
    }

    /**
     * @return string
     */
    public function getResetToken()
    {
        return md5($this->created.$this->updated.$this->user_id);
    }

    public function setAuthKey()
    {
        $this->setAttribute('auth_key', static::generateAuthKey(time()));
        $this->save(false);
    }

    /**
     * @param $auth_key
     * @param $reset_token
     * @return array|bool|null|\yii\db\ActiveRecord|User
     */
    public static function findForReset($auth_key, $reset_token)
    {
        if (!empty($auth_key) && !empty($reset_token)) {
            $user = self::findBySql("SELECT * FROM `".self::tableName()."` WHERE auth_key = :auth_key AND MD5(CONCAT(created, updated, user_id)) = :reset_token", [':auth_key' => $auth_key, ':reset_token' => $reset_token])->one();

            return ($user) ? $user : false;
        }

        return false;
    }
}

backend/controllers/RoleController.php
<?php

namespace backend\controllers;

use backend\components\BackendController;
use Yii;
use common\models\Role;
use common\models\RoleSearch;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

/**
 * RoleController implements the CRUD actions for Role model.
 */
class RoleController extends BackendController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    ['allow' => true, 'actions' => ['index', 'create', 'update', 'delete', 'view'], 'roles' => ['@']],
                ],
            ],
        ];
    }

    /**
     * Lists all Role models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RoleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Role model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Role model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Role();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->role_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Role model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->role_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Role model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Role model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Role the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Role::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\components\BackendController;
use backend\widgets\FileUpload;
use Yii;
use common\models\User;
use common\models\UserSearch;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends BackendController
{
    public function init()
    {
        parent::init();

        $this->setThemeLayout('page');
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    ['allow' => true, 'actions' => ['index', 'create', 'update', 'delete', 'view'], 'roles' => ['admin']],
                    ['allow' => true, 'actions' => ['profile', 'upload-files', 'change'], 'roles' => ['admin', 'partner']],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new User(['scenario' => 'new']);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->user_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        /* @var User $model */
        $model = $this->findModel($id);
        $model->setScenario('edit');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->user_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws \Exception
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionProfile()
    {
        /* @var $model User */
        $model = $this->findModel(Yii::$app->user->identity->getId());

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Профиль сохранен успешно!');

            return $this->redirect(['user/profile']);
        } else {
            return $this->render('profile', [
                'model' => $model,
            ]);
        }
    }

    public function actionChange()
    {
        /* @var $user User */
        $user = User::findOne(Yii::$app->user->identity->user_id);
        $user->setScenario('password_change');
        $user->setAttribute('password', '');

        if (Yii::$app->request->getIsPost()) {
            if ($user->load(Yii::$app->request->post()) && $user->validatePassword()) {
                $user->save(false);

                Yii::$app->session->setFlash('success', 'Пароль успешно изменен!');

                return $this->redirect(['change']);
            }
        }

        return $this->render('change', [
            'user' => $user
        ]);
    }

    public function actionUploadFiles()
    {
        FileUpload::uploadFile(['jpg', 'png', 'gif']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/theme/gentelella/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\elfinder\InputFile;

/* @var $this yii\web\View */
/* @var common\models\User $model */
/* @var $partner common\models\PartnerInfo */
/* @var $form yii\widgets\ActiveForm */

//$partner->name = $model->username;
//var_dump($partner);
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <ul class="nav nav-tabs" id="tabs">
        <li class="active"><a href="#user" data-toggle="tab">Пользователь</a></li>
        <li><a href="#partner" data-toggle="tab">Партнер</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane in active" id="user">
            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
                    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
                    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>
                </div>
                <div class="col-md-3">
                    <?= $form->field($model, 'role_id')->dropDownList(\common\models\Role::getRolesList()) ?>
                    <?= $form->field($model, 'status')->dropDownList([1 => 'Включено', 2 => 'Выключено']) ?>
                </div>
                <div class="col-md-3">

                    <div class="form-group" style="width: 180px;">
                        <label class="control-label"><?php echo $model->getAttributeLabel('image'); ?></label>
                        <?php echo InputFile::widget([
                            'language'      => 'ru',
                            'name'          => 'User[image]',
                            'value'         => $model->image,
                            'id'            => 'user-image',
                            'controller'    => 'elfinder',
                            'filter'        => 'image',
                            'template'      => '<div class="thumbnail text-center">'.(($model->image) ? '<img src="'.$model->image.'" id="image-user-image">' : '<i class="fa fa-image" style="font-size: 150px" id="icon-user-image"></i>').'<div class="input-group">{input}<span class="input-group-btn">{button}</span></div></div>',
                            'options'       => ['class' => 'form-control'],
                            'buttonOptions' => ['class' => 'btn btn-default'],
                            'multiple'      => false,
                        ]); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/theme/gentelella/user/change.php
<?php

use \yii\widgets\ActiveForm;

/* @var $this \yii\web\View */
/* @var $user \common\models\User */

$this->title = 'Смена пароля';
$this->params['breadcrumbs'][] = ['label' => 'Панель управления', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => 'Профиль', 'url' => ['user/profile']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="padding-md">
    <div class="row">
        <div class="col-md-9">
            <div class="partner-profile-password">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1 class="panel-title">Смена пароля</h1>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-6">
                            <?php if (Yii::$app->session->hasFlash('success')) { ?>
                                <div class="alert alert-success">
                                    <i class="fa fa-check-circle"></i> <?php echo Yii::$app->session->getFlash('success'); ?>
                                    <a class="pull-right button-close"><i class="fa fa-times"></i></a>
                                </div>
                            <?php } ?>
                            <?php $form = ActiveForm::begin(); ?>
                            <?php echo $form->field($user, 'old_password')->passwordInput(); ?>
                            <?php echo $form->field($user, 'password')->passwordInput(); ?>
                            <?php echo $form->field($user, 'confirm')->passwordInput(); ?>
                            <?php echo \yii\helpers\Html::submitButton('Сохранить', ['class' => 'btn btn-success']); ?>
                            <?php ActiveForm::end(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/theme/gentelella/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Добавление нового пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Панель управления', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create padding-md">
    <div class="row">
        <div class="col-md-12">
            <h2><i class="fa fa-user-plus"></i> <?= Html::encode($this->title) ?></h2>

            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>
</div>

backend/views/theme/gentelella/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use backend\assets\theme\gentelella\FormAsset;

/* @var $this yii\web\View */
/* @var $searchModel common\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = ['label' => 'Панель управления', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = $this->title;

FormAsset::register($this);

?>
<div class="padding-md">
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-md-7">
                    <p class="lead"><i class="fa fa-list"></i> <?= Html::encode($this->title) ?></p>
                </div>
                <div class="col-md-5">
                    <p class="pull-right">
                        <?= Html::a('Создать пользователя', ['create'], ['class' => 'btn btn-success']) ?>
                    </p>
                </div>
            </div>

            <?php if (Yii::$app->session->hasFlash('success')) { ?>
                <div class="alert alert-success">
                    <i class="fa fa-check-circle"></i> <?php echo Yii::$app->session->getFlash('success'); ?>
                    <a class="pull-right button-close"><i class="fa fa-times"></i></a>
                </div>
            <?php } ?>

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    'user_id',
                    'username',
                    'email:email',
                    'role_id' => [
                        'attribute' => 'role_id',
                        'format' => 'html',
                        'value' => function($model) {
                            if ($model->role_id) {
                                return $model->role_id . ': ' . Html::a($model->role->name, ['role/update', 'id' => $model->role_id]);
                            } else {
                                return '';
                            }
                        }
                    ],
                    'created' => [
                        'attribute' => 'created',
                        'value' => function($model) {
                            return date('d.m.Y H:i:s', strtotime($model->created));
                        }
                    ],
                    // 'updated',
                    'status' => [
                        'attribute' => 'status',
                        'value' => function($model) {
                            return \common\components\Status::getStatus($model->status);
                        }
                    ],
                    // 'auth_key',
                    // 'username',

                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
        </div>
    </div>
</div>

backend/views/theme/gentelella/user/profile.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\components\Image;
use backend\widgets\FileUpload;

/* @var $model \common\models\User */
/* @var $partner \common\models\PartnerInfo */
/* @var $this \yii\web\View */

$this->title = 'Редактировать профиль';

$this->params['breadcrumbs'][] = ['label' => 'Панель управления', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="padding-md">
    <div class="row">
        <div class="col-sm-12">
            <p class="lead"><i class="fa fa-edit"></i> <?php echo Html::encode($this->title); ?></p>

            <?php if (Yii::$app->session->hasFlash('success')) { ?>
                <div class="alert alert-success">
                    <i class="fa fa-check-circle"></i> <?php echo Yii::$app->session->getFlash('success'); ?>
                    <a class="pull-right button-close"><i class="fa fa-times"></i></a>
                </div>
            <?php } ?>

            <?php $form = ActiveForm::begin(); ?>
            <div class="row">
                <div class="col-sm-4">
                    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
                    <?= $form->field($partner, 'contact_person')->textInput(); ?>
                    <?= $form->field($partner, 'email')->textInput(); ?>
                    <?= $form->field($partner, 'name')->textInput(); ?>
                </div>
                <div class="col-sm-4">
                    <?= $form->field($partner, 'inn')->textInput(); ?>
                    <?= $form->field($partner, 'kpp')->textInput(); ?>
                    <?= $form->field($partner, 'f_address')->textInput(); ?>
                    <?= $form->field($partner, 'y_address')->textInput(); ?>
                </div>
                <div class="col-sm-4">
                    <?php echo FileUpload::widget([
                        'model' => $model,
                        'name' => 'image',
                        'attribute' => 'image',
                        'uploadUrl' => \yii\helpers\Url::to(['user/upload-files']),
                        'buttonUpload' => 'Загрузить',
                        'thumb' => Image::resize($model->image, FileUpload::THUMB_WIDTH, FileUpload::THUMB_HEIGHT)
                    ]) ?>
                </div>
            </div>
            <div class="btn-group">
                <?= Html::a('Вернуться назад', Yii::$app->request->referrer, ['class' => 'btn btn-danger']); ?>
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']); ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/theme/gentelella/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Update User: ' . ' ' . $model->user_id;
$this->title = 'Обновление пользователя: ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Панель управления', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => $model->user_id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-update padding-md">

    <div class="row">
        <div class="col-md-12">
            <h2><i class="fa fa-edit"></i> <?= Html::encode($this->title) ?></h2>

            <?= $this->render('_form', [
                'model' => $model,
                'partner' => $partner,
            ]) ?>
        </div>
    </div>

</div>

backend/views/theme/gentelella/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Панель управления', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="padding-md">
    <div class="row">
        <div class="col-md-12">
            <h2><i class="fa fa-street-view"></i> <?= Html::encode($this->title) ?></h2>
            <p>
                <?= Html::a('Обновить', ['user/update', 'id' => $model->user_id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Удалить', ['user/delete', 'id' => $model->user_id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </p>
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'user_id',
                    'email:email',
                    'password',
                    'role_id',
                    'created',
                    'updated',
                    'status',
                    //'auth_key',
                    'username',
                ],
            ]) ?>
        </div>
    </div>
</div>